name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    # continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        experimental: [false]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Coding standards
        if: matrix.analysis
        run: vendor/bin/psalm.phar

      - name: Static analysis
        if: matrix.analysis
        run: vendor/bin/phpstan analyse -c phpstan.neon --no-progress --ansi

      #- name: Tests
      #  run: vendor/bin/phpunit --coverage-clover clover.xml

      # - name: Upload coverage results to Coveralls
      #   if: matrix.analysis
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     composer require php-coveralls/php-coveralls -n -W
      #     vendor/bin/php-coveralls --coverage_clover=clover.xml -v
